apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-deployment
  labels:
    app: sample-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-web
  template:
    metadata:
      labels:
        app: sample-web
    spec:
      imagePullSecrets:
      - name: aws
      containers:
      - name: sample-web
        image: 712380418412.dkr.ecr.ap-southeast-1.amazonaws.com/sample-web:1.0
        ports:
        - containerPort: 80
