apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-web.fullname" . }}
  labels:
    {{- include "sample-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
