apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-deployment
  labels:
    app: sample-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-web
  template:
    metadata:
      labels:
        app: sample-web
    spec:
      containers:
      - name: sample-web
        image: $IMAGE
        ports:
        - containerPort: 80
