kind: Service
apiVersion: v1
metadata:
 name: mongo
spec:
 type: ClusterIP
 ports:
 - port: 27017
   targetPort: 27017
---
kind: Endpoints
apiVersion: v1
metadata:
 name: mongo
subsets:
 - addresses:
     - ip: 10.240.0.4
   ports:
     - port: 27017